# required functions to get everything that we need
import subprocess
def execute_command(command):

    """
    Execute a CLI command and return the output and error messages.
    Parameters:
    -  command [str]: The CLI command to execute.

    Returns:
    - output (str): The output generated by the command. 
                    A zip file containing the NFDB fire polygons (for large fires)
    - error (str): The error message generated by the command, if any.

    """

    try:

        # execute the command and capture the output and error messages

        process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, error = process.communicate()

        output = output.decode("utf-8")
        error = error.decode("utf-8")

        # return the output and error messages
        return output, error

    except Exception as e:

        # if an exception occurs, return the exception message as an error
        return None, str(e)